CCM-1866: Handle unexpected 504
NHSDigital/communications-manager-api pull request #268
Opened 2023-10-04 12:48 UTC by Kennedy1265

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [x] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2023-10-05 08:20 UTC, PhilipSkinner commented on tests/development/content_types/test_content_type_negotiation.py
>      if resp.status_code == 429:
I wonder if we should move this out into a helper then we can call it with the `resp` value - that way we only have the retry logic in a single place?

I'm thinking we have 3 functions - 

* `handle_retry(resp)`
* `handle_429_retry(resp)`
* `handle_504_retry(resp)`

; where the `handle_retry` func executes the two other functions in order. The reason for this is that in certain places we want a 429 to be thrown but still want to retry on a 504, and vice versa.

2023-10-05 08:21 UTC, PhilipSkinner commented on tests/lib/assertions.py
> +from .constants import *
Sonar won't like this, if you want access to all constants do `import lib.constants as constants` then access the constants as `constants.CORS_METHODS` etc

2023-10-05 08:22 UTC, PhilipSkinner commented
Missing 504 checks on the sandbox 429 tests

2023-10-05 08:26 UTC, PhilipSkinner requested changes
Please see prior comments

2023-10-05 11:55 UTC, PhilipSkinner commented on tests/test_endpoints.py
>      if resp.status_code == 429:
We should import the Error_Handler here for these tests instead of having the same logic here

2023-10-06 09:51 UTC, Ian-Hodges commented on tests/test_endpoints.py
> +from lib.constants import UNEXPECTED_429, UNEXPECTED_504
Very minor, these constants are no longer used.

2023-10-06 10:14 UTC, Ian-Hodges approved these changes
Looks good to me and Phil's comments have been addressed.

2023-10-09 08:23 UTC, PhilipSkinner approved these changes

2023-10-09 08:23 UTC, merged