CCM-1620: Post test failures to teams
NHSDigital/communications-manager-api pull request #286
Opened 2023-10-13 09:04 UTC by Kennedy1265

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2023-10-13 09:35 UTC, Kennedy1265 commented
![image](https://github.com/NHSDigital/communications-manager-api/assets/28391437/ae18eb45-6658-470f-ae3f-0135d8fa769b)

2023-10-19 12:31 UTC, PhilipSkinner commented on azure/nightly-int-qa-pipeline.yml
> +      -d '{"@type":"MessageCard","@context":"http://schema.org/extensions","themeColor":"ff0000","title":"Nightly Internal QA Test Run Failed","text":"https://dev.azure.com/NHSD-APIM/API%20Platform/_
I wonder if you want to template this alerting so we don't replicate the action for sending the message?

2023-10-20 06:59 UTC, PhilipSkinner requested changes
Please see previous comments

2023-10-20 09:48 UTC, Kennedy1265 commented
closing due to further testing

2023-10-20 09:48 UTC, closed without merging