CCM-2036: prefer headed for 500 status code
NHSDigital/communications-manager-api pull request #306
Opened 2023-10-30 17:36 UTC by adadigital

## Summary

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Checklist
* [ ] Brief description of work completed, and any technical decisions made as part of the PR
* [ ] PR link added as a comment to the relevant JIRA ticket
* [ ] Branch deployed to a dynamic env - link to deployment pipeline
* [ ] PR link shared on Slack and/or Teams
* [ ] 1 reviews received

2023-11-03 12:25 UTC, PhilipSkinner requested changes
Just one minor change please!

2023-11-03 12:50 UTC, adadigital commented on tests/docs/partials/timeouts/test_500_internal_error_prefer.rst
> +Scenario: An API consumer submitting a request with a 500 prefer header receives a 500 'internal server error' response
I've just been looking over the structure of the docs and I'm not quite sure where it fits? Just under `tests/docs/partials` maybe?

2023-11-03 15:27 UTC, PhilipSkinner commented on tests/docs/partials/timeouts/test_500_internal_error_prefer.rst
> +Scenario: An API consumer submitting a request with a 500 prefer header receives a 500 'internal server error' response
yeah I think thats fine, we can always move it into a sub-folder if/when we add more similar tests

2023-11-06 13:34 UTC, PhilipSkinner approved these changes

2023-11-07 09:39 UTC, merged